[versions]
activityCompose = "1.10.1"
activityComposeVersion = "1.8.2"
agp = "8.13.0"
androidxActivityCompose = "1.7.2"
androidxHiltCompiler = "1.1.0"
androidxMaterial = "1.4.3"
androidxMaterial3 = "1.4.0-alpha13"
bom = "<VERSION>"
bomVersion = "2.31.3"
comGoogleDaggerHiltAndroid = "2.56"
comGoogleDaggerHiltAndroid2 = "2.40"
comGoogleDaggerHiltAndroidCompiler = "2.44"
compiler = "1.5.15"
composeBom = "2025.03.00"
coreKtxVersion = "1.12.0"
dagger = "2.56"
daggerCompiler = "2.56"
googleHiltAndroid = "2.48"
googleHiltAndroidCompiler = "2.28-alpha"
googleHiltAndroidCompilerVersion = "2.40"
googleHiltAndroidGradlePlugin = "2.48.1"
googleHiltAndroidVersion = "2.48.1"
googleHiltCompiler = "2.55"
googleHiltCompilerVersion = "2.56"
gson = "2.10.1"
hiltAndroid = "2.51.1"
hiltAndroidCompiler = "2.51.1"
hiltAndroidCompilerVersion = "2.48"
hiltAndroidGradlePlugin = "2.55"
hiltAndroidGradlePluginVersion = "2.56"
hiltAndroidVersion = "2.50"
hiltCommon = "1.2.0"
hiltCommonVersion = "1.0.0"
hiltCompiler = "2.50"
hiltCompilerVersion = "2.48.1"
junitJunit = "4.12"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxCoroutinesCore = "1.7.1"
kotlinxCoroutinesTest = "1.7.1"
kotlinxMetadataJvm = "LATEST_KOTLINX_METADATA_VERSION"
lifecycleRuntimeKtx = "2.8.7"
lifecycleViewmodelCompose = "2.9.3"
material = "1.12.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
material3 = "1.3.1"
material3Version = "1.3.2"
materialVersion = "1.7.8"
mockitoCore = "2.11.0"
mockitoCoreVersion = "2.1.0"
mockitoInline = "2.13.0"
mockitoJunitJupiter = "5.4.0"
mockitoKotlin = "1"
mockitoMockitoCore = "5.4.0"
mockk = "{version}"
mockkAndroid = "VERSION"
mockkAndroidVersion = "1.13.5"
mockkCommon = "1.11.0"
mockkMockk = "1.11.0"
mockkVersion = "1.0"
moshi = "1.14.0"
moshiKotlin = "LATEST_VERSION"
moshiKotlinCodegen = "1.14.0"
moshiKotlinCodegenVersion = "1.9.2"
moshiKotlinVersion = "1.14.0"
moshiVersion = "1.12.0"
navigationFragmentKtx = "2.8.9"
navigationUiKtx = "2.8.9"
powermockApiMockito = "1.6.2"
powermockApiMockito2 = "1.7.3"
powermockCore = "1.7.3"
powermockMockitoReleaseFull = "1.6.0'"
powermockModuleJunit4 = "1.6.2"
powermockModuleJunit4Version = "1.7.3"
roomKtx = "2.7.0"
roomRuntime = "2.6.1"
roomRuntimeVersion = "2.7.0"
runtime = "1.7.8"
squareupMoshi = "1.15.0"
squareupMoshiKotlin = "1.12.0"
squareupMoshiKotlinCodegen = "1.15.0"
squareupMoshiKotlinVersion = "1.15.0"
ui = "1.9.1"
uiTooling = "1.9.0"
fragmentCompose = "1.8.9"
# Navigation libraries versions
nav3Core = "1.0.0-alpha01"
lifecycleViewmodelNav3 = "1.0.0-alpha01"
androidxMaterial3Version = "1.4.0"



[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-activity-compose-v172 = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-activity-compose-v182 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hiltCommon" }
androidx-hilt-common-v100 = { module = "androidx.hilt:hilt-common", version.ref = "hiltCommonVersion" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCommonVersion" }
androidx-hilt-compiler-v110 = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHiltCompiler" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCommon" }
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltCommonVersion" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltCommonVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material-v143 = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material3-v132 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-material3-v140alpha13 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerCompiler" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvm" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3Version" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-ktx-v270 = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-runtime-v270 = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomKtx" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
bom = { module = "software.amazon.awssdk:bom", version.ref = "bom" }
bom-v2313 = { module = "software.amazon.awssdk:bom", version.ref = "bomVersion" }
compiler = { module = "androidx.compose.compiler:compiler" }
dynamodb-enhanced = { module = "software.amazon.awssdk:dynamodb-enhanced" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android-compiler-v228alpha = { module = "com.google.dagger:hilt-android-compiler", version.ref = "googleHiltAndroidCompiler" }
hilt-android-compiler-v240 = { module = "com.google.dagger:hilt-android-compiler", version.ref = "googleHiltAndroidCompilerVersion" }
hilt-android-compiler-v244 = { module = "com.google.dagger:hilt-android-compiler", version.ref = "comGoogleDaggerHiltAndroidCompiler" }
hilt-android-compiler-v248 = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompilerVersion" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-gradle-plugin-v2481 = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "googleHiltAndroidGradlePlugin" }
hilt-android-gradle-plugin-v256 = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePluginVersion" }
hilt-android-v240 = { module = "com.google.dagger:hilt-android", version.ref = "comGoogleDaggerHiltAndroid2" }
hilt-android-v248 = { module = "com.google.dagger:hilt-android", version.ref = "googleHiltAndroid" }
hilt-android-v2481 = { module = "com.google.dagger:hilt-android", version.ref = "googleHiltAndroidVersion" }
hilt-android-v250 = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-android-v256 = { module = "com.google.dagger:hilt-android", version.ref = "comGoogleDaggerHiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
hilt-compiler-v2481 = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompilerVersion" }
hilt-compiler-v255 = { module = "com.google.dagger:hilt-compiler", version.ref = "googleHiltCompiler" }
hilt-compiler-v256 = { module = "com.google.dagger:hilt-compiler", version.ref = "googleHiltCompilerVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v412 = { module = "junit:junit", version.ref = "junitJunit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
material3 = { module = "androidx.compose.material3:material3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-core-v210 = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
mockito-core-v540 = { module = "org.mockito:mockito-core", version.ref = "mockitoMockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockitoJunitJupiter" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
mockk-android-v1135 = { module = "io.mockk:mockk-android", version.ref = "mockkAndroidVersion" }
mockk-common = { module = "io.mockk:mockk-common", version.ref = "mockkCommon" }
mockk-v10 = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
mockk-v1110 = { module = "io.mockk:mockk", version.ref = "mockkMockk" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen" }
moshi-kotlin-codegen-v1150 = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "squareupMoshiKotlinCodegen" }
moshi-kotlin-codegen-v192 = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegenVersion" }
moshi-kotlin-v1120 = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "squareupMoshiKotlin" }
moshi-kotlin-v1150 = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "squareupMoshiKotlinVersion" }
moshi-kotlin-vlatestversion = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
moshi-v1120 = { module = "com.squareup.moshi:moshi", version.ref = "moshiVersion" }
moshi-v1150 = { module = "com.squareup.moshi:moshi", version.ref = "squareupMoshi" }
powermock-api-mockito = { module = "org.powermock:powermock-api-mockito", version.ref = "powermockApiMockito" }
powermock-api-mockito2 = { module = "org.powermock:powermock-api-mockito2", version.ref = "powermockApiMockito2" }
powermock-core = { module = "org.powermock:powermock-core", version.ref = "powermockCore" }
powermock-mockito-release-full = { module = "org.powermock:powermock-mockito-release-full", version.ref = "powermockMockitoReleaseFull" }
powermock-module-junit4 = { module = "org.powermock:powermock-module-junit4", version.ref = "powermockModuleJunit4" }
powermock-module-junit4-v173 = { module = "org.powermock:powermock-module-junit4", version.ref = "powermockModuleJunit4Version" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
squareup-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlinVersion" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragmentCompose" }
# Navigatio libraries
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxMaterial3Version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
