[versions]
agp = "8.8.1"
bom = "<VERSION>"
bomVersion = "2.31.3"
compiler = "1.5.15"
googleHiltAndroid = "2.48"
hiltAndroid = "2.51.1"
hiltAndroidCompiler = "2.51.1"
hiltAndroidCompilerVersion = "2.48"
hiltAndroidGradlePlugin = "2.55"
hiltAndroidVersion = "2.50"
hiltCompiler = "2.50"
junitJunit = "4.12"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
mockitoCore = "2.11.0"
mockk = "{version}"
navigationFragmentKtx = "2.8.9"
navigationUiKtx = "2.8.9"
powermockApiMockito = "1.6.2"
powermockModuleJunit4 = "1.6.2"
runtime = "1.7.8"

[libraries]
androidx-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
bom = { module = "software.amazon.awssdk:bom", version.ref = "bom" }
bom-v2313 = { module = "software.amazon.awssdk:bom", version.ref = "bomVersion" }
compiler = { module = "androidx.compose.compiler:compiler" }
dynamodb-enhanced = { module = "software.amazon.awssdk:dynamodb-enhanced" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android-compiler-v248 = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompilerVersion" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-v248 = { module = "com.google.dagger:hilt-android", version.ref = "googleHiltAndroid" }
hilt-android-v250 = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v412 = { module = "junit:junit", version.ref = "junitJunit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
powermock-api-mockito = { module = "org.powermock:powermock-api-mockito", version.ref = "powermockApiMockito" }
powermock-module-junit4 = { module = "org.powermock:powermock-module-junit4", version.ref = "powermockModuleJunit4" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

